### ISSUE TITLE
[Bug] incorrect boderpx in Bottom

### ISSUE THREAD

**Issue by leihaojun** [veltza/st-sx#11]
borderpx = 20

![image](https://github.com/user-attachments/assets/88ad9a79-5e83-49a1-9042-ac2ed626cd94)

borderpx = 2
![image](https://github.com/user-attachments/assets/6672e8ea-dc4e-4237-a611-1ecfc813375b)

There seems to be more boderpx  Bottom than in the other direction. And the right borderpx also  more than left.

**Comment by leihaojun** [comment]
Well this doesn't seem to be a bug, just the space left after calculating the number of rows and columns related to font size and window size

**Comment by veltza** [comment]
Yeah, it's not a bug. It's the [anysize patch](https://st.suckless.org/patches/anysize/) that works that way. The patch is designed for window manager users, but if you don't use any window manager or don't like it, you can disable it [here](https://github.com/veltza/st-sx/blob/1f3e76c648d5dc6711270641850302cd50a12fd7/config.def.h#L244-L245) or via Xresources.
