### ISSUE TITLE
[Feature Request] set font style

### ISSUE THREAD

**Issue by leihaojun** [veltza/st-sx#3]
Thank you for making this great tool, but I can't seem to find the configuration of setting the font style, the current font seems a little small to me, can you add the font style Settings such as (Regular,Medium)?

**Comment by veltza** [comment]
You can use the `style` property in the font definition.

For example, like this in your [config.h](https://github.com/veltza/st-sx/blob/cc42fea183fdca9d6319b6bf65816ff1aaf7db11/config.def.h#L8) file:

```c
static char *font = "JetBrains Mono:style=Medium:size=10:antialias=true:autohint=true";
```
Or in your [.Xresources](https://github.com/veltza/st-sx/blob/main/xresources-example) file:

```
St.font:    JetBrains Mono:style=Medium:size=10:antialias=true:autohint=true
```

**Comment by leihaojun** [comment]
it work  thanks
