### ISSUE TITLE
[Feature Request] auto scroll  up  when cursor above the st window

### ISSUE THREAD

**Issue by leihaojun** [veltza/st-sx#4]
Other terminals such as foot kitty will automatically scroll up after holding down the left mouse button and moving up to mark the area where the terminal is located.

However, st does not seem to support this, resulting in st can only use the mouse to select the text in the current area, but can not select the previous text。

foot terminal

https://github.com/user-attachments/assets/230e8b39-eb46-4c15-bf80-78b48ca1ee12

**Comment by veltza** [comment]
Unfortunately, you can't select text and scroll the screen at the same time with your mouse. But you can do that in keyboard selection mode by using your keyboard.

I'll see if I can find any easy ways to improve the mouse selection.
